name: Build and create release asset

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  asset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison byacc make cmake m4
          sudo apt-get install -y gsoap libgsoap-dev
      - name: Build binary
        run: |
          cmake -B build . -DUSE_GSOAP_STATIC_LIB=1 -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.architecture }}
          cmake --build build
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/wsdd
          asset_name: wsdd-${{ matrix.architecture }}-linux
          asset_content_type: application/octet-stream
